[tool.poetry]
name = "lecture-1"
version = "0.1.0"
description = ""
authors = ["Povodir1 <pvdr26@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
